//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int IDContact { get; set; }
        public string TenKH { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Title { get; set; }
        public string CONTENT { get; set; }
    }
}
