//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewProduct
    {
        public int ReProID { get; set; }
        public string ReName { get; set; }
        public string ReContent { get; set; }
        public Nullable<System.DateTime> ReDate { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
