//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int IDVoucher { get; set; }
        public string VoucherName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string VoucherDes { get; set; }
        public string CouponCode { get; set; }
    }
}
